version: "3.8"

services:

  products_db:
    image: postgres:16-alpine
    container_name: products_db
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: mantissa
      POSTGRES_PASSWORD: mantissa
      POSTGRES_DB: mantissa
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5433:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management console