version: "3.8"

services:

  products_db:
    image: postgres:16-alpine
    container_name: history_db
    environment:
      POSTGRES_HOST: history_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: history
      POSTGRES_PASSWORD: history
      POSTGRES_DB: history
    volumes:
      - ./history_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5434:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management console